#include "dip_list.h"

const DIPPath DIP_PATHS[DIP_FILES_COUNT] = {
    { "DATA\\GER\\STARTUP.PAK", "DATA\\ENG\\STARTUP.PAK", "HISTORY.DIP", "HISTORY.DIP" },
    { "DATA\\GER\\STARTUP.PAK", "DATA\\ENG\\STARTUP.PAK", "LOLINTRO.DIP", "LOLINTRO.DIP" }
};
